FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /expense-worker ./cmd/expense-worker

FROM alpine:3.20

RUN adduser -D appuser
WORKDIR /app
COPY --from=builder --chmod=755 /expense-worker /app/expense-worker
USER appuser

CMD ["/app/expense-worker"]
